### PR TITLE
Fix a duplication in the databasename property

### LINKED ISSUE #162: Some properties have cosmosdb.cosmosdb in the name
## Problem Statement
Some properties, like `connect.cosmosdb.cosmosdb.databasename` should really be just `connect.cosmosdb.databasename`

https://github.com/microsoft/kafka-connect-cosmosdb/blob/bf072b6032248a6ed1101e9ce0a67304f65cb768/src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java#L37

## Proposed Solution
Just deprecate the old properties, and create a new one, referencing the same get/set methods

### PR DESCRIPTION
**Pull request by marcelopio**
The property databasename full name was connect.cosmosdb.cosmosdb.databasename, which had a duplication that was not needed. This fix the duplication, deprecating the old one

## Type of PR

- [x] Documentation changes
- [x] Code changes
- [x] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
Fix a duplication in the full name of databasename, causing it to have cosmosdb twice (cosmosdb.cosmosdb)

## Review notes
I could not run the integration-tests since it can only be run on Windows, and I am on a Linux platform. We should refactor the integration tests to run also on Linux, since it will be easier to integrate with GitHub CI

## Issues Closed or Referenced

- Closes #162

### CODE REVIEW

File: src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java [hunk 1]
```diff
@@ -34,7 +34,8 @@
                     "Task poll interval", SettingDefaults.TASK_POLL_INTERVAL, this::setTaskPollInterval, this::getTaskPollInterval),
             new Setting(PREFIX+".connection.endpoint", "The Cosmos DB endpoint.", "CosmosDB Endpoint", this::setEndpoint, this::getEndpoint),
             new Setting(PREFIX+".master.key", "The connection master key.", "Master Key", this::setKey, this::getKey),
-            new Setting(PREFIX+".cosmosdb.databasename", "The Cosmos DB target database.", "CosmosDB Database Name", this::setDatabaseName, this::getDatabaseName),
+            new Setting(PREFIX+".cosmosdb.databasename", "(Deprecated) The Cosmos DB target database.", "CosmosDB Database Name", this::setDatabaseName, this::getDatabaseName),
```
Comment (ryancrawcour) [inline src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java:37]: i would just remove this (Deprecated). we will note this as a breaking change and will bump the version number when we merge and push a new release.

**Review by ryancrawcour — CHANGES_REQUESTED** [review]

**Review by ryancrawcour — APPROVED** [review]
